name: Setup Go
description: Setup Go runtime
inputs:
  go-version:
    description: "go version to setup"
    required: false
    default: "1.21"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - uses: actions/cache@v3
      with:
        path: ~/go/bin/
        key: ${{ runner.os }}-go-blogsync-200423.0756
        restore-keys: |
          ${{ runner.os }}-go-blogsync-200423.0756
