name: "[Reusable workflows] push to hatena blog"

on:
  workflow_call:
    inputs:
      local_root:
        default: "entries"
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  push:
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'skip-push') }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: setup
        uses: hatena/hatenablog-workflows/.github/actions/setup@fa544a63e845030ff65e35d78847e2bc2cab981e # v2.0.2
      - name: Get changed files
        id: changed-files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          list-files: shell # default 'none'. Disables listing of matching files.
          filters: |
            changes:
              - added|modified: ${{ inputs.local_root }}/**/*.md
      - name: blogsync push
        run: |
          for file in ${{ steps.changed-files.outputs.changes_files }}; do
            draft=$(yq --front-matter=extract 'select(.Draft == true)' "$file")
            if [[ -z "$draft" ]]; then
              blogsync push "$file"
            fi
          done
