name: "[Reusable workflows] upload images"

on:
  workflow_call:
    secrets:
      OWNER_API_KEY:
        required: true
    outputs:
      revision:
        value: ${{ jobs.upload-image.outputs.revision }}

jobs:
  upload-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      revision: ${{ steps.commit-and-push.outputs.revision }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Get changed files
        id: changed-entries
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          list-files: shell # default 'none'. Disables listing of matching files.
          filters: |
            changes:
              - added|modified: entries/**/*.md
              - added|modified: draft_entries/**/*.md
      - name: set owner
        id: set-owner
        run: |
          owner=$(yq "..|.owner|select(.)" blogsync.yaml)
          if [[ -z "$owner" ]]; then
            owner=$(yq "..|.username|select(.)" blogsync.yaml)
          fi
          echo "OWNER_ID=$owner" >> $GITHUB_OUTPUT
      - name: Download the script
        run: |
          curl -fsSL -o /tmp/fotolife-client.py https://raw.githubusercontent.com/hatena/hatenablog-workflows/v1/fotolife-client.py
          chmod +x /tmp/fotolife-client.py
      - name: List all changed files markdown files
        if: ${{ steps.changed-entries.outputs.changes == 'true' }}
        run: |
          for f in ${{ steps.changed-entries.outputs.changes_files }}; do
            python3 /tmp/fotolife-client.py "$f"
          done
        env:
          HATENA_ID: ${{ steps.set-owner.outputs.OWNER_ID }}
          OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
      - name: commit & push
        id: commit-and-push
        run: |
          git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ $(git diff) -eq 0 ]]; then
            exit 0
          fi

          git add .
          git commit -m "upload images to fotolife"
          git push

          revision=$(git rev-parse HEAD)
          echo "REVISION=$revision" >> $GITHUB_OUTPUT
