name: create draft

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Title"
        required: true
      additional-draft-pr-body-path:
        description: "Path to additional draft PR body"
        required: false
        default: "./.github/PULL_REQUEST_TEMPLATE.md"

jobs:
  create-draft:
    # uses: hatena/hatenablog-workflows/.github/workflows/create-draft.yaml@f42256332f4838de9799dbed0b1ac6d3ce2224f2 # v1.3.3
    uses: ./.github/workflows/_create-draft.yaml
    with:
      title: ${{ github.event.inputs.title }}
      draft: true
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
