name: initialize

on:
  workflow_dispatch:
    inputs:
      is_draft_included:
        description: "同期対象に下書きを含める(未公開の記事が commit されます)"
        required: true
        type: boolean

jobs:
  initialize:
    uses: hatena/hatenablog-workflows/.github/workflows/initialize.yaml@f42256332f4838de9799dbed0b1ac6d3ce2224f2 # v1.3.3
    with:
      is_draft_included: ${{ inputs.is_draft_included }}
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
