name: post to hatena blog

on:
  issues:
    types: [closed]

jobs:
  post:
    if: startsWith(github.event.issue.title, 'Post:')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/cache@v1
        with:
          path: ~/go/bin/
          key: ${{ runner.os }}-go-blogsync-200423.0756
          restore-keys: |
            ${{ runner.os }}-go-blogsync-200423.0756
      - uses: actions/checkout@v3
      - name: fetch main
        run: git fetch origin main
      - name: Setup blogsync
        run: |
          if ! (type ~/go/bin/blogsync > /dev/null 2>&1); then
            go get github.com/x-motemen/blogsync;
          fi
          echo -e "${BSY}" > blogsync.yaml
        env:
          BSY: ${{ secrets.BSY }}
      - name: blogsync post
        run: |
          echo '${{ env.BODY }}' \
          | grep '^path:' \
          | sed -e "s/path:\(.*\)[ \f\n\r\t]/\1/g" \
          | xargs -t -n1 -I{} ~/go/bin/blogsync post --title=draft --draft --custom-path={} ${{ secrets.DOMAIN }} ""
        env:
          BODY: ${{ github.event.issue.body }}
          DOMAIN: ${{ secrets.DOMAIN }}
      - name: push to repository
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "generated from ${{ github.event.issue.html_url }}"
          git push
