name: post to hatena blog

on:
  workflow_dispatch:
  issues:
    types: [closed]

jobs:
  post:
    if: ${{ startsWith(github.event.issue.title, 'Post:') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Setup blogsync
        uses: ./.github/actions/setup-blogsync
        with:
          bsy: ${{ secrets.BSY }}
      - name: post
        run: |
          echo '${{ github.event.issue.body }}' \
          | grep '^path:' \
          | sed -e "s/path:\(.*\)[ \f\n\r\t]/\1/g" \
          | xargs -t -n1 -I{} ~/go/bin/blogsync post --title=draft --draft --custom-path={} ${{ env.DOMAIN }} ""
        env:
          DOMAIN: ${{ secrets.DOMAIN }}

      # git push
      - name: git diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - if: steps.diff.outcome == 'failure'
        name: git push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "[auto commit] generated from ${{ github.event_name == 'issue' && github.event.issue.html_url || env.WORKFLOW_URL }}"
          git push
        env:
          WORKFLOW_URL: "https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"
