name: pull from hatena blog

on:
  workflow_dispatch:
  issues:
    types: [closed]

jobs:
  pull:
    if: ${{ startsWith(github.event.issue.title, 'Pull:') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup Go
        uses: guitarrapc/blog/.github/actions/setup-go@main
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Setup blogsync
        uses: guitarrapc/blog/.github/actions/setup-blogsync@main
        with:
          bsy: ${{ secrets.BSY }}
      - name: pull blog
        run: ~/go/bin/blogsync pull ${{ env.DOMAIN }}
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
      - name: Git Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "[auto commit] pull all post from hatenablog via ${{ github.event_name == 'issue' && github.event.issue.html_url || env.WORKFLOW_URL }}"
        env:
          WORKFLOW_URL: "https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"
