name: push to hatena blog

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/cache@v1
        with:
          path: ~/go/bin/
          key: ${{ runner.os }}-go-blogsync-200423.0756
          restore-keys: |
            ${{ runner.os }}-go-blogsync-200423.0756
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: fetch main and PR merged ref
        run: |
          git fetch origin main
          git fetch origin "${HEAD_REF}"
          echo "MAIN_SHA=$(git rev-parse origin/main~)" >> "$GITHUB_ENV"
          :
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
      - name: Setup blogsync
        run: |
          if ! (type ~/go/bin/blogsync > /dev/null 2>&1); then
            go get github.com/x-motemen/blogsync;
          fi
          echo -e "${BSY}" > blogsync.yaml
        env:
          BSY: ${{ secrets.BSY }}
      - name: blogsync push
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          git diff --name-only ${{env.MAIN_SHA}} ${{ github.event.pull_request.head.sha }} -- \
          | grep "^${{ secrets.DOMAIN }}" \
          | xargs -t -n1 ~/go/bin/blogsync push
