name: 記事更新

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  push:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - name: Setup blogsync
        uses: ./.github/actions/setup-blogsync
        with:
          bsy: ${{ secrets.BSY }}
      - name: git fetch pull request state
        id: git-fetch
        run: |
          git fetch origin main
          git fetch origin ${{ github.event.pull_request.head.ref }}
          echo "sha=$(git rev-parse origin/main~)" | tee -a "$GITHUB_OUTPUT"
      - name: push blog
        run: |
          git diff --name-only ${{ steps.git-fetch.outputs.sha }} ${{ github.event.pull_request.head.sha }} -- \
          | grep "^${{ env.DOMAIN }}" \
          | xargs -t -n1 blogsync push
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@master
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
