name: push draft to hatena blog

on:
  pull_request:
    paths:
      - "draft_entries/**"

jobs:
  push-draft:
    #uses: hatena/hatenablog-workflows/.github/workflows/push-draft.yaml@v1
    uses: ./.github/workflows/_push-draft.yaml
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
