name: push published entries


on:
  pull_request:
    paths:
      - "entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@f42256332f4838de9799dbed0b1ac6d3ce2224f2 # v1.3.3
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
