name: push to hatena blog

on: 
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tag:
    name: push
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - uses: actions/cache@v1
      with:
        path: ~/go/bin/
        key: ${{ runner.os }}-go-blogsync-200423.0756
        restore-keys: |
          ${{ runner.os }}-go-blogsync-200423.0756
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with: 
        fetch-depth: 3
        
    - run: |
        git fetch origin main
        git fetch origin ${{github.event.pull_request.head.ref}}
        echo "MAIN_SHA=$(git rev-parse origin/main~)" >> $GITHUB_ENV
        :
    - name: Setup blogsync
      env:
        BSY: ${{ secrets.BSY }}
      run: |
        if !(type ~/go/bin/blogsync > /dev/null 2>&1); then
          go get github.com/x-motemen/blogsync;
        fi
        echo -e ${BSY} > blogsync.yaml
    - name: push
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        git diff --name-only ${{env.MAIN_SHA}} ${{github.event.pull_request.head.sha}} -- \
        | grep "^${{ secrets.DOMAIN }}" \
        | xargs -t -n1 ~/go/bin/blogsync push
    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@master
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
