name: 記事の校正 by label
on:
  pull_request:
    branches: [main]
    types: [labeled]

jobs:
  textlint:
    if: ${{ github.event.label.name == 'textlint' }}
    uses: guitarrapc/blog/.github/workflows/textlint.yaml@main
    secrets:
      personal_access_token: ${{ secrets.GITHUB_TOKEN }}
