name: 記事の校正 by label
on:
  pull_request:
    branches: [main]
    types: [labeled]

jobs:
  trigger:
    if: ${{ github.event.label.name == 'textlint' }}
    uses: guitarrapc/blog/.github/workflows/textlint.yaml@main
