name: 記事の校正
on:
  pull_request:
    branches: [main]
    paths:
      - "draft_entries/**/*.md"
      - "entries/**/*.md"
      - .github/workflows/textlint.yaml
      - .textlintrc.json
      - package*.json
  workflow_call:
  workflow_dispatch:

# run `npx textlint --fix ./guitarrapc-tech.hatenablog.com/entry/**/*.md` to fix lint errors.

jobs:
  textlint-lint:
    strategy:
      fail-fast: false
      matrix:
        year:
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019
          - 2020
          - 2021
          - 2022
          - 2023
          - 2024
          - 2025
          - 2026
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
      - name: restore textlint
        run: npm ci
      - name: textlint (draft)
        run: npm run "lintdraft"
      - name: textlint
        run: npm run "lint${{ matrix.year }}"

  textlint:
    needs: textlint-lint
    runs-on: ubuntu-24.04
    steps:
      - name: completed
        run: echo "textlint job completed"
